### ISSUE TITLE
zlib dependency in libpng and netcdf

### ISSUE THREAD

**Issue by climbfuji** [NOAA-EMC/NCEPLIBS-external#46]
Release ufs-v1.0.0 has limitations wrt to building libpng and netcdf. One either has to build both or skip both. This is because both depend on libz and we wanted to avoid having two different versions used by libpng and netcdf (in case one is built and the other is used from a pre-installed package).

The correct way to do this is the following logic:
(1) if both BUIILD_PNG and BUILD_NETCDF are ON
    - if BUILD_LIBZ is ON, build it and make sure to link against it
    - if BUILD_LIBZ is OFF, look for it (use ZLIB_ROOT as hint)
    - which should be the default?
(2) if BUILD_PNG or BUILD_NETCDF is ON, the other is OFF
    - look for existing LIBZ (use ZLIB_ROOT as hint) and use it for both, do not build it
    - automatically forces BUILD_LIBZ to OFF
(3) if BUILD_PNG and BUILD_NETCDF are OFF
    - don't build LIBZ

(3) is already implemented, (1) and (2) not

**Comment by edwardhartnett** [comment]
This may be a good place to describe a feature added to netcdf-c-4.7.4, and which will appear in the next release of netcdf-fortran (which should happen soon). I added an nc_def_var_szip() function to allow netCDF users to use szip compression, in addition to zlib compression.

(This is part of a larger effort of mine to add more compression options to netCDF.)

The szip library is optionally present for HDF5. If it was present for HDF5, then netcdf-c detects that, and it is available to netCDF users as well. (Similarly, if it's available in netCDF C, then netcdf-fortran can use it.) The functions nc_def_var_szip()/nf_def_var_szip() are always present, but in builds without szip they return error NC_ENOTBUILT.

Szip has proven popular in the NASA community, where they value its speed.

These new compression methods are being added to make them available in the UFS to meet future needs wrt data increases due to model resolution increases. So I believe it would be useful to have NCEPLIBS-external build netcdf-c with szip if it is going to build netcdf.

**Comment by climbfuji** [comment]
Closing this - dependencies are addressed properly in spack-stack.
